using System;
using System.Collections.Generic;
namespace Calculator;

// Should I feel dirty for using `internal` here?
public class ParserException(string commandLine, string message, int index, int length) : Exception
{
    private string internalMessage = message;
    public string CommandLine { get; } = commandLine;
    public int Index { get; } = index;
    public int Length { get; } = length;
    public override string Message
    {
        get => $"at index {Index}: {internalMessage}";
    }
}

public class BasicParserException(string message) : Exception
{
    public override string Message { get; } = message;
}

public struct ParserExceptionFactory(string commandLine)
{
    private string commandLine = commandLine;

    public ParserException MakeException(string message, int index, int length) =>
        new ParserException(commandLine, message, index, length);

    public Exception MakeException(string message, Lexeme lexeme) => lexeme.index switch
    {
        null => new BasicParserException($"at <auto-generated> token: {message}"),
        int idx => new ParserException(commandLine, message, idx, lexeme.token.Length),
    };
}

// TODO: Rewrite this code to look at operator lexemes based on the lexeme ID instead of the actual
// token that they hold.
public static class Parser
{
    private struct EndTestResult(Nullable<Lexeme> lexeme, bool endOfStream)
    {
        public Nullable<Lexeme> Lexeme { get; } = lexeme;
        public bool EndOfStream { get; } = endOfStream;

        public static EndTestResult Ye(Lexeme lexeme) => new EndTestResult(lexeme, false);
        public static EndTestResult StreamEnd() => new EndTestResult(null, true);
        public static EndTestResult Nah() => new EndTestResult(null, false);
    }

    // This function returns `null` on error, and should never throw an exception. I find this fine
    // since there's only 1 obvious way this thing can fail. Is this idiomatic C#? I don't think so,
    // but it makes sense to me,,,
    private static IExpression? Merge(IExpression? left, IExpression? right, LexemeID? op) =>
        right switch
        {
            null => null,
            _ =>
                left switch
                {
                    null => right,
                    _ => op switch
                    {
                        LexemeID.Add => new Add(left, right),
                        LexemeID.Subtract => new Subtract(left, right),
                        LexemeID.Multiply => new Multiply(left, right),
                        LexemeID.Divide => new Divide(left, right),
                        LexemeID.Exponent => new Exponent(left, right),
                        _ => throw new ArgumentException("Invalid operator lexeme here"),
                    },
                },
        };

    private struct ParserStuff
    {
        public ParserExceptionFactory ParserMaker { get; }
        public List<Exception> Errors { get; } = new();

        [Obsolete("Parameterless constructor called by mistake", true)]
        public ParserStuff() { }

        public ParserStuff(ParserExceptionFactory maker)
        {
            ParserMaker = maker;
        }
    }

    private static IExpression? MaybeRecurse(IEnumerator<Lexeme> tokens, ref ParserStuff stuff, uint depth)
    {
        return tokens.Current.ID == LexemeID.IncPrecedence ?
            ParseRec(tokens, ref stuff, (tokens) => tokens.MoveNext() switch
            {
                true => tokens.Current.ID == LexemeID.DecPrecedence ? EndTestResult.Nah() : EndTestResult.Ye(tokens.Current),
                false => EndTestResult.StreamEnd(),
            }, depth + 1) : new Number(tokens.Current.token);
    }

    private static IExpression? ParseRec(
        IEnumerator<Lexeme> tokens,
        ref ParserStuff stuff,
        Func<IEnumerator<Lexeme>, EndTestResult> tryNext,
        uint depth)
    {
        (IExpression? left, IExpression? mid, IExpression? right) = (null, null, null);
        LexemeID? oldAddOperator = null;
        LexemeID? oldMultOperator = null;

        if (!tryNext(tokens).Lexeme.HasValue)
        {
            return null;
        }

        if (MaybeRecurse(tokens, ref stuff, depth) is IExpression resolved)
        {
            right = resolved;
        }
        else
        {
            stuff.Errors.Add(stuff.ParserMaker.MakeException("Empty parenthesis", tokens.Current));
        }
        EndTestResult checkLexeme = EndTestResult.Nah(); // just initialize with *something* idfk

        // read two tokens at a time, first one should be an operator, second should be a number
        while ((checkLexeme = tryNext(tokens)).Lexeme.HasValue)
        {
            Lexeme op = tokens.Current;
            if (!tryNext(tokens).Lexeme.HasValue)
            {
                stuff.Errors.Add(stuff.ParserMaker.MakeException($"Unbalanced operator \"{op.token}\"", op));

                continue;
            } else if(tokens.Current.IsOperator()) {
                stuff.Errors.Add(stuff.ParserMaker.MakeException($"Expected operand, got operator", tokens.Current));

                // xdfjnkgsdkljfhgdslkgjdhsfklfjghsdflkg
            }

            // TODO: Handle token here not being an valid one for an operand.
            // What should be done on such an event? Try to see if the next token is an operand,
            // imo.

            IExpression? operand = MaybeRecurse(tokens, ref stuff, depth);
            if (operand is null)
            {
                // Empty expression here, instead of garbage. We're fine to just add an error and
                // move on?
                stuff.Errors.Add(stuff.ParserMaker.MakeException("Empty parenthesis? idk anymore,", tokens.Current));
            }

            switch (op.ID)
            {
                case LexemeID.Exponent:
                    if (operand is IExpression _ && right is IExpression _)
                    {
                        right = new Exponent(right, operand);
                    }
                    break;
                case LexemeID.Multiply:
                case LexemeID.Divide:
                    mid = Merge(mid, right, oldMultOperator);
                    oldMultOperator = op.ID; // these two lines might have to be inside the above if
                    right = operand;
                    break;
                case LexemeID.Add:
                case LexemeID.Subtract:
                    mid = Merge(mid, right, oldMultOperator);
                    right = operand;
                    oldMultOperator = null;
                    left = Merge(left, mid, oldAddOperator);
                    oldAddOperator = op.ID;
                    // mid = new Number(operand);
                    mid = null;
                    break;
                default:
                    stuff.Errors.Add(stuff.ParserMaker.MakeException($"Invalid operator \"{op.token}\".", op));
                    break;
            }
        }

        if (checkLexeme.EndOfStream && depth > 0)
        {
            // throw new NotImplementedException("Unbalanced parentheses");
            // TODO: Save the beginning lexeme for the open parenthesis for use in these errors
            stuff.Errors.Add(stuff.ParserMaker.MakeException("Unclosed parenthesis", checkLexeme.Lexeme.Value));
        }

        // TODO: Handle more null cases here, as there are now WAYYYYYYY more possibilities.
        mid = Merge(mid, right, oldMultOperator);
        return (left, mid, oldAddOperator) switch
        {
            (null, null, _) => throw new Exception("All are null. How???"),
            (null, _, _) => mid,
            (_, null, _) => left,
            (_, _, LexemeID.Add) => new Add(left, mid),
            (_, _, LexemeID.Subtract) => new Subtract(left, mid),
            _ => throw new Exception("meow :3"),
        };
    }

    public static IExpression Parse(IEnumerable<Lexeme> tokens, ParserExceptionFactory errorMaker)
    {
        ParserStuff stuff = new(errorMaker);

        using (var enumerator = tokens.GetEnumerator())
        {
            IExpression? expr = ParseRec(enumerator, ref stuff, (tokens) => tokens.MoveNext() switch
            {
                true => EndTestResult.Ye(tokens.Current),
                false => EndTestResult.StreamEnd(),
            }, 0);

            if (stuff.Errors.Count > 0)
            {
                throw new AggregateException(stuff.Errors);
            }

            return expr;
        }
    }
}

public class YourMom
{
    private string status = "fat";
    public void PrintStatus() => Console.WriteLine($"yo mama so {status}");
}

