using System;
using System.Collections.Generic;
namespace Calculator;

// Should I feel dirty for using `internal` here?
public class ParserException(string commandLine, string message, int index, int length) : Exception
{
    private string internalMessage = message;
    public string CommandLine { get; } = commandLine;
    public int Index { get; } = index;
    public int Length { get; } = length;
    public override string Message
    {
        get => $"at index {Index}: {internalMessage}";
    }
}

public class BasicParserException(string message) : Exception
{
    public override string Message { get; } = message;
}

public struct ParserExceptionFactory(string commandLine)
{
    private string commandLine = commandLine;

    public ParserException MakeException(string message, int index, int length) =>
        new ParserException(commandLine, message, index, length);

    public Exception MakeException(string message, SequentialLexeme lexeme) => lexeme.Index switch
    {
        null => new BasicParserException($"at <auto-generated> token: {message}"),
        int idx => new ParserException(commandLine, message, idx, lexeme.Token.Length),
    };
}

// TODO: Rewrite this code to look at operator lexemes based on the lexeme ID instead of the actual
// token that they hold.
public static class Parser
{
    private struct EndTestResult(SequentialLexeme? lexeme, bool endOfStream)
    {
        public SequentialLexeme? Lexeme { get; } = lexeme;
        public bool EndOfStream { get; } = endOfStream;

        public static EndTestResult Ye(SequentialLexeme lexeme) => new EndTestResult(lexeme, false);
        public static EndTestResult StreamEnd() => new EndTestResult(null, true);
        public static EndTestResult Nah() => new EndTestResult(null, false);
    }

    // This function returns `null` on error, and should never throw an exception. I find this fine
    // since there's only 1 obvious way this thing can fail. Is this idiomatic C#? I don't think so,
    // but it makes sense to me,,,
    private static IExpression? Merge(IExpression? left, IExpression? right, LexemeID? op) =>
        right switch
        {
            null => null,
            _ =>
                left switch
                {
                    null => right,
                    _ => op switch
                    {
                        LexemeID.Add => new Add(left, right),
                        LexemeID.Subtract => new Subtract(left, right),
                        LexemeID.Multiply => new Multiply(left, right),
                        LexemeID.Divide => new Divide(left, right),
                        LexemeID.Exponent => new Exponent(left, right),
                        _ => throw new ArgumentException("Invalid operator lexeme here"),
                    },
                },
        };

    private struct ParserStuff
    {
        public ParserExceptionFactory ErrorMaker { get; }
        public List<Exception> Errors { get; } = new();

        [Obsolete("Parameterless constructor called by mistake", true)]
        public ParserStuff() { }

        public ParserStuff(ParserExceptionFactory maker)
        {
            ErrorMaker = maker;
        }
    }

    private static IExpression? MaybeRecurse(IEnumerator<SequentialLexeme> tokens, ref ParserStuff stuff, uint depth)
    {
        return tokens.Current.ID == LexemeID.IncPrecedence ?
            ParseRec(tokens, ref stuff, (tokens) => tokens.MoveNext() switch
            {
                true => tokens.Current.ID == LexemeID.DecPrecedence ? EndTestResult.Nah() : EndTestResult.Ye(tokens.Current),
                false => EndTestResult.StreamEnd(),
            }, depth + 1) : new Number(tokens.Current.Token);
    }

    private static bool FindValidOperand(
        IEnumerator<SequentialLexeme> tokens,
        ref ParserStuff stuff,
        Func<IEnumerator<SequentialLexeme>, EndTestResult> tryNext
        )
    {
        bool wasInvalid = false;

        while (true)
        {
            if (!tryNext(tokens).Lexeme.HasValue)
            {
                return true;
            }

            var lexeme = tokens.Current;

            if (lexeme.ID == LexemeID.Invalid)
            {
                stuff.Errors.Add(stuff.ErrorMaker.MakeException($"Expected number or opening parenthesis, got {lexeme.ID.ToString()}", lexeme));
                wasInvalid = true;
                continue;
            }

            if (lexeme.IsOperator())
            {
                if (wasInvalid)
                {
                    wasInvalid = false;
                }
                else
                {
                    stuff.Errors.Add(stuff.ErrorMaker.MakeException($"Expected number or opening parenthesis, got {lexeme.ID.ToString()}", lexeme));
                }
                continue;
            }

            break;
        }

        return false;
    }


    private static IExpression? ParseRec(
        IEnumerator<SequentialLexeme> tokens,
        ref ParserStuff stuff,
        Func<IEnumerator<SequentialLexeme>, EndTestResult> tryNext,
        uint depth)
    {
        (IExpression? left, IExpression? mid, IExpression? right) = (null, null, null);
        LexemeID? oldAddOperator = null;
        LexemeID? oldMultOperator = null;

        if (FindValidOperand(tokens, ref stuff, tryNext))
        {
            return null;
        }

        // This right here is the first token to actually make any sense. Ensure that it's
        // either a number or some expression surrounded by parenthesis, and if so, if the
        // parenthesis contain anything.
        {
            SequentialLexeme firstLexeme = tokens.Current;

            if (MaybeRecurse(tokens, ref stuff, depth) is IExpression resolved)
            {
                right = resolved;
            }
            else if (tokens.Current.SeqIndex - firstLexeme.SeqIndex < 2)
            {
                stuff.Errors.Add(stuff.ErrorMaker.MakeException("Empty parenthesis", firstLexeme));
            }
        }

        EndTestResult checkLexeme = EndTestResult.Nah(); // just initialize with *something* idfk

        // read two tokens at a time, first one should be an operator, second should be a number
        while ((checkLexeme = tryNext(tokens)).Lexeme.HasValue)
        {
            SequentialLexeme op = tokens.Current;
            if (op.ID == LexemeID.Invalid || op.ID == LexemeID.None)
            {
                stuff.Errors.Add(stuff.ErrorMaker.MakeException($"Expected operator, got {op.ID.ToString()}", op));
                continue;
            }

            if (FindValidOperand(tokens, ref stuff, tryNext))
            {
                stuff.Errors.Add(stuff.ErrorMaker.MakeException($"Unbalanced operator \"{op.Token}\"", op));
                continue;
            }

            SequentialLexeme openParenthLexeme = tokens.Current;
            IExpression? operand = MaybeRecurse(tokens, ref stuff, depth);
            if (operand is null)
            {
                if (tokens.Current.SeqIndex - openParenthLexeme.SeqIndex < 2)
                {
                    stuff.Errors.Add(stuff.ErrorMaker.MakeException("Empty parenthesis", openParenthLexeme));
                }
            }

            switch (op.ID)
            {
                case LexemeID.Exponent:
                    if (operand is IExpression _ && right is IExpression _)
                    {
                        right = new Exponent(right, operand);
                    }
                    break;
                case LexemeID.Multiply:
                case LexemeID.Divide:
                    mid = Merge(mid, right, oldMultOperator);
                    oldMultOperator = op.ID; // these two lines might have to be inside the above if
                    right = operand;
                    break;
                case LexemeID.Add:
                case LexemeID.Subtract:
                    mid = Merge(mid, right, oldMultOperator);
                    right = operand;
                    oldMultOperator = null;
                    left = Merge(left, mid, oldAddOperator);
                    oldAddOperator = op.ID;
                    mid = null;
                    break;
                default:
                    stuff.Errors.Add(stuff.ErrorMaker.MakeException($"Invalid operator \"{op.Token}\".", op));
                    break;
            }
        }

        if (checkLexeme.EndOfStream && depth > 0)
        {
            // throw new NotImplementedException("Unbalanced parentheses");
            // TODO: Save the beginning lexeme for the open parenthesis for use in these errors
            stuff.Errors.Add(stuff.ErrorMaker.MakeException("Unclosed parenthesis", checkLexeme.Lexeme.Value));
        }

        mid = Merge(mid, right, oldMultOperator);
        return (left, mid, oldAddOperator) switch
        {
            (null, null, _) => null,
            (null, _, _) => mid,
            (_, null, _) => left,
            (_, _, LexemeID.Add) => new Add(left, mid),
            (_, _, LexemeID.Subtract) => new Subtract(left, mid),
            _ => throw new Exception("meow :3"),
        };
    }

    public static IExpression? Parse(IEnumerable<SequentialLexeme> tokens, ParserExceptionFactory errorMaker)
    {
        ParserStuff stuff = new(errorMaker);

        using (var enumerator = tokens.GetEnumerator())
        {
            IExpression? expr = ParseRec(enumerator, ref stuff, (tokens) => tokens.MoveNext() switch
            {
                true => EndTestResult.Ye(tokens.Current),
                false => EndTestResult.StreamEnd(),
            }, 0);

            if (stuff.Errors.Count > 0)
            {
                throw new AggregateException(stuff.Errors);
            }

            return expr;
        }
    }
}

